/*
* DO NOT EDIT THIS FILE
*/
#ifndef ARGSPARSE_H
#define ARGSPARSE_H

#include "configp.h"

void parse_arguments( int argc, char **argv, Config * conf);
void check_file();
void check_debug_mode(Config conf);

#endif
