/*
* DO NOT EDIT THIS FILE
*/
#ifndef ARGSPARSE_H
#define ARGSPARSE_H

#define MAX_FILE_COUNT 10
#define MAX_LENGTH_COMMAND 25
#define MAX_ARGUMENT_COUNT 5

int parse_arguments( int argc, char **argv, char acommand[MAX_LENGTH_COMMAND] );
void check_file();
void check_debug_mode();

#endif